## Colors configuration
[colors.primary]
background = "#030504"
foreground = "#ABB2BF"

[colors.normal]
black   = "#32363D"
red     = "#E06B74"
green   = "#f6bd60"
yellow  = "#aacc00"
blue    = "#00b4d8"
magenta = "#98c1d9"
cyan    = "#aacc00"
white   = "#ABB2BF"

[colors.bright]
black   = "#50545B"
red     = "#EA757E"
green   = "#A2CD83"
yellow  = "#EFCA84"
blue    = "#6CB8F9"
magenta = "#D282E7"
cyan    = "#5FC0CC"
white   = "#B5BCC9"
